services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ark-backend
        restart: unless-stopped
        working_dir: /app
        volumes:
            - .:/app
        networks:
            - ark-network
        depends_on:
            - database
        ports:
            - "3080:3000"
        environment:
            - NODE_ENV=production
            - DATABASE_URL=postgresql://ark_user:ark_password@ark-db:5432/ark_registry

    database:
        platform: linux/amd64
        image: postgis/postgis:latest
        container_name: ark-db
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - ark-network
        ports:
            - "5433:5432"

networks:
    ark-network:
        driver: bridge
        name: ark-network

volumes:
    postgres_data:
